export const elementIds = [
  '#qr-preview',
  '#qr-content',
  '#qr-margin-slider',
  '#qr-margin-slider-value',
  '#choose-file-input',
  '#choose-file-btn',
  '#logo-group',
  '#logo-filename',
  '#logo-margin-control',
  '#logo-margin-slider',
  '#logo-margin-slider-value',
  '#remove-logo',
  '#background-rotation-control',
  '#qr-background-rotation-slider',
  '#qr-background-rotation-slider-value',
] as const;
